FROM centos:7

COPY resources/rhit-root-ca.crt /etc/pki/ca-trust/source/anchors/
RUN update-ca-trust extract

RUN yum -y install make jq perl-XML-XPath

ENV OC_VERSION="4.5"
RUN curl -Ls https://mirror.openshift.com/pub/openshift-v4/clients/oc/$OC_VERSION/linux/oc.tar.gz | tar -zx && \
    mv oc /usr/local/bin


ENV JQ_VERSION="1.6"
RUN curl -Lo /usr/local/bin/jq https://github.com/stedolan/jq/releases/download/jq-${JQ_VERSION}/jq-linux64 && \
    chmod +x /usr/local/bin/jq
