{
 "title": "Workload App",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "AMQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sent Messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(workload_app_service_requests_total{name=\"amq_sender\"})",
     "legendFormat": "Sent Messages"
    }
   ]
  },
  {
   "title": "Sender Downtime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(workload_app_service_downtime_seconds{name=\"amq_sender\"})"
    }
   ]
  },
  {
   "title": "Sender Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(workload_app_service_requests_errors_total{name=\"amq_sender\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workload_app_service_up{name=\"amq_sender\"}",
     "legendFormat": "{{exported_service}}"
    },
    {
     "expr": "workload_app_service_up{name=\"amq_receiver\"}",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  {
   "title": "Received Messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(workload_app_service_requests_total{name=\"amq_receiver\"})"
    }
   ]
  },
  {
   "title": "Receiver Downtime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(workload_app_service_downtime_seconds{name=\"amq_receiver\"})"
    }
   ]
  },
  {
   "title": "Receiver Errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(workload_app_service_requests_errors_total{name=\"amq_receiver\"})"
    }
   ]
  },
  { "title": "AMQ CRUD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Cycles",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(workload_app_service_requests_total{name=\"amq_crud\"})"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(workload_app_service_downtime_seconds{name=\"amq_crud\"})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(workload_app_service_requests_errors_total{name=\"amq_crud\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workload_app_service_up{name=\"amq_crud\"}",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  { "title": "AMQ Console", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(workload_app_service_requests_total{name=\"amqconsole_service\"})"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(workload_app_service_downtime_seconds{name=\"amqconsole_service\"})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(workload_app_service_requests_errors_total{name=\"amqconsole_service\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workload_app_service_up{name=\"amqconsole_service\"}",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  { "title": "3Scale", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(workload_app_service_requests_total{name=\"3scale_service\"})"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(workload_app_service_downtime_seconds{name=\"3scale_service\"})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(workload_app_service_requests_errors_total{name=\"3scale_service\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workload_app_service_up{name=\"3scale_service\"}",
     "legendFormat": "{{exported_service}}"
    }
   ]
  },
  { "title": "SSO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(workload_app_service_requests_total{name=\"sso_service\"})"
    }
   ]
  },
  {
   "title": "Downtime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(workload_app_service_downtime_seconds{name=\"sso_service\"})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(workload_app_service_requests_errors_total{name=\"sso_service\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workload_app_service_up{name=\"sso_service\"}",
     "legendFormat": "{{exported_service}}"
    }
   ]
  }
 ]
}